apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  namespace: default
  labels:
    app: nginx
    tier: fronted
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
  serviceAccountName: jack-sa
