apiVersion: v1
kind: Service
metadata:
  name: external-nagios-svc
  namespace: default
spec:
  type: ExternalName
  externalName: nagios.xxx.xxx
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 0
  selector: {}
  