apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: csuxh/jackhttpd:v1.0
    imagePullPolicy: IfNotPresent
  initContainers:
  - name: init-something
    image: busybox:1.30.0
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'sleep 10']
