apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe-http
  namespace: default
spec:
  containers:
  - name: liveness-container
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "touch /tmp/test; sleep 30; rm -rf /tmp/test; sleep 3600"]
    livenessProbe:
      exec:
        command: ["test", "-e", "/tmp/test"]
      initialDelaySeconds: 1
      periodSeconds: 3 
