apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    app: pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s_pv/
