apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-service
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006
  type: NodePort
