apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: pvc01
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mypvcpod 
  namespace: default
spec:
  containers:
    - name: mypod
      image: ikubernetes/myapp:v1
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: pvc01 
