apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/nfs/pv1
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  accessModes: 
  - ReadWriteMany
  capacity:
    storage: 1Gi 
  hostPath:
    path: /data/nfs/pv2
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/nfs/pv3
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/nfs/pv4
    type: DirectoryOrCreate
